spring:
  application:
    name: ServiceSpringBoot

#Hibernate Properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 5N6a2h3u0e8l6G-1
    url: jdbc:mysql://localhost:3306/blog_system_db


  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

#JWT Properties

app:
  jwt-secret: ASJF6GK65FG8RT31F64SAD688JK8658FJ4L38FDSG9S97GH969JK7HK9586JH875J75SDG75SADFASDFSVCXZVZXCGEWRQWY76RY867E6Y8TR66VNCVNH6D8JD8H6K86S67G
  jwt-expiration-milliseconds: 604800000

